#!/usr/bin/env python3
"""Render PipeWire filter-chain from layout57.json.

Stereo sink cs8409_speakers → 4ch analog-surround-40.
Implements the decoded Equalization32 / splitter path. Not Mozart,
BuzzKill, ControlFreak, or thermal (undocumented). Hard clamp stands
in for those limiters. Woofer invert is from the mic sweep, not Apple XML.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAYOUT = Path(__file__).resolve().parent / "layout57.json"
OUT = ROOT / "60-cs8409-crossover.conf"

BQ = {
    "lowpass": "bq_lowpass",
    "highpass": "bq_highpass",
    "peaking": "bq_peaking",
    "notch": "bq_notch",
}

# HP/LP gain in Apple XML is the Butterworth −3 dB point, not extra cut.
PASS_TYPES = {"lowpass", "highpass"}


def chain_by_key(data: dict) -> dict:
    return {c["key"]: c for c in data["chain"]}


def bands(fn: dict) -> list[dict]:
    return list(fn.get("bands_l") or [])


def spa_type(b: dict) -> str:
    t = b["type"]
    if t == "notch" and abs(float(b["gain_db"])) > 0.5:
        return "bq_peaking"
    return BQ.get(t, "bq_peaking")


def spa_gain(b: dict) -> float:
    if b["type"] in PASS_TYPES:
        return 0.0
    return float(b["gain_db"])


def skip(b: dict) -> bool:
    if b["type"] == "peaking" and abs(float(b["gain_db"])) < 0.05:
        return True
    return False


def filters_block(items: list[dict], extra: list[dict] | None = None) -> str:
    rows = list(extra or [])
    for b in items:
        if skip(b):
            continue
        rows.append(
            {
                "type": spa_type(b),
                "freq": float(b["freq_hz"]),
                "q": float(b["q"]),
                "gain": spa_gain(b),
            }
        )
    pad = "                                "
    lines = []
    for r in rows:
        lines.append(
            f'{pad}{{ type = "{r["type"]}" freq = {r["freq"]:.4f} '
            f'q = {r["q"]:.4f} gain = {r["gain"]:.3f} }}'
        )
    return "\n".join(lines)


def main() -> int:
    data = json.loads(LAYOUT.read_text())
    c = chain_by_key(data)
    pre = (
        bands(c["DspFunction0"])
        + bands(c["DspFunction3"])
        + bands(c["DspFunction5"])
    )
    tw = bands(c["DspFunction8"])
    wf = bands(c["DspFunction9"])
    pad = "                                "
    pre_txt = filters_block(pre)
    head_txt = (
        f'{pad}{{ type = "bq_highshelf" freq = 0.0 q = 1.0 gain = -6.000 }}\n'
        + pre_txt
        + f'\n{pad}{{ type = "bq_highshelf" freq = 0.0 q = 1.0 gain = 1.500 }}'
    )
    tw_txt = filters_block(tw)
    wf_txt = filters_block(wf)

    text = f"""# Generated by applehda/render_filter.py from layout57.json.
# MacBookPro14,3: stereo sink → 4ch MAX98706. Do not edit by hand.
#
# Keep davidjo for amp/TDM. This is CoreAudio Equalization32 + splitter.
# Not Mozart / BuzzKill / ControlFreak / thermal. Clamp is the limiter.
# Woofer invert: internal-mic sweep (26 dB hole at 1 kHz without it).
# Parked 800 Hz LR4: 60-cs8409-lr4.conf
context.modules = [
    {{ name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {{
            node.description = "MacBook speakers"
            media.name       = "MacBook speakers"
            filter.graph = {{
                nodes = [
                    {{
                        name = pre
                        type = builtin
                        label = param_eq
                        config = {{
                            filters = [
{head_txt}
                            ]
                        }}
                    }}
                    {{
                        name = tw
                        type = builtin
                        label = param_eq
                        config = {{
                            filters = [
{tw_txt}
                            ]
                        }}
                    }}
                    {{
                        name = wf
                        type = builtin
                        label = param_eq
                        config = {{
                            filters = [
{wf_txt}
                            ]
                        }}
                    }}
                    {{ name = invL type = builtin label = invert }}
                    {{ name = invR type = builtin label = invert }}
                    {{
                        name = clTwL
                        type = builtin
                        label = clamp
                        control = {{ "Min" = -0.98 "Max" = 0.98 }}
                    }}
                    {{
                        name = clTwR
                        type = builtin
                        label = clamp
                        control = {{ "Min" = -0.98 "Max" = 0.98 }}
                    }}
                    {{
                        name = clWfL
                        type = builtin
                        label = clamp
                        control = {{ "Min" = -0.98 "Max" = 0.98 }}
                    }}
                    {{
                        name = clWfR
                        type = builtin
                        label = clamp
                        control = {{ "Min" = -0.98 "Max" = 0.98 }}
                    }}
                ]
                links = [
                    {{ output = "pre:Out 1" input = "tw:In 1" }}
                    {{ output = "pre:Out 2" input = "tw:In 2" }}
                    {{ output = "pre:Out 1" input = "wf:In 1" }}
                    {{ output = "pre:Out 2" input = "wf:In 2" }}
                    {{ output = "tw:Out 1" input = "clTwL:In" }}
                    {{ output = "tw:Out 2" input = "clTwR:In" }}
                    {{ output = "wf:Out 1" input = "invL:In" }}
                    {{ output = "wf:Out 2" input = "invR:In" }}
                    {{ output = "invL:Out" input = "clWfL:In" }}
                    {{ output = "invR:Out" input = "clWfR:In" }}
                ]
                inputs  = [ "pre:In 1" "pre:In 2" ]
                outputs = [ "clTwL:Out" "clTwR:Out" "clWfL:Out" "clWfR:Out" ]
            }}
            capture.props = {{
                node.name             = "cs8409_speakers"
                node.description      = "MacBook speakers"
                media.class           = "Audio/Sink"
                audio.position        = [ FL FR ]
                audio.channels        = 2
                audio.rate            = 44100
                priority.session      = 1400
                priority.driver       = 1400
            }}
            playback.props = {{
                node.name             = "cs8409_speakers.playback"
                media.class           = "Stream/Output/Audio"
                audio.position        = [ FL FR RL RR ]
                audio.channels        = 4
                audio.rate            = 44100
                stream.dont-remix     = true
                channelmix.disable    = true
                node.passive          = true
                node.dont-fallback    = true
                target.object         = "alsa_output.pci-0000_00_1f.3.analog-surround-40"
            }}
        }}
    }}
]
"""
    OUT.write_text(text)
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
